spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create
#
## ??? ????? ??????? ???? ???????????? SQL ? ???? ddl.sql ????? ? ?????? ???????
#spring.jpa.properties.hibernate.hbm2ddl.auto_quote_keyword=true
#spring.jpa.properties.hibernate.schema_generation.scripts.action=create
#spring.jpa.properties.hibernate.schema_generation.scripts.create_target=schema_dump.sql

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-ms=1800000
app.jwt.refresh-token-expiration-ms=1209600000